export const SITE = {
  name: "Agency Orchestrator",
  short: "ao",
  platform: "https://aiolaola.com",
  repo: "https://github.com/jnMetaCode/agency-orchestrator",
  npm: "https://www.npmjs.com/package/agency-orchestrator",
  rolesRepo: "https://github.com/jnMetaCode/agency-agents-zh",
  issues: "https://github.com/jnMetaCode/agency-orchestrator/issues",
  changelog: "https://github.com/jnMetaCode/agency-orchestrator/blob/main/CHANGELOG.md",
  license: "https://github.com/jnMetaCode/agency-orchestrator/blob/main/LICENSE",
  evalFindings: "https://github.com/jnMetaCode/agency-orchestrator/blob/main/EVAL_FINDINGS.md",
  releases: "https://github.com/jnMetaCode/agency-orchestrator/releases/latest",
  install: "npm i -g agency-orchestrator",
  sponsorEmail: "jnMetaCode@qq.com",
  sponsorContact: "mailto:jnMetaCode@qq.com?subject=Sponsorship%20-%20agency-agents",
  providersKeyed: ["DeepSeek", "Claude", "OpenAI", "Gemini", "Ollama", "Moonshot", "硅基流动", "OpenRouter"],
  providersKeyfree: ["claude-code CLI", "Antigravity CLI", "copilot-cli", "codex-cli", "openclaw-cli", "hermes-cli", "codebuddy-cli", "cline-cli", "Ollama 本地"],
};
